name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [13.7.0]
    runs-on: ${{ matrix.os }}
    name: node ${{ matrix.node }} on ${{ matrix.os }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: setup linux fs watchers
        if: runner.os == 'Linux'
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
      - name: npm install
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm install
      - name: code quality
        if: matrix.node == '13.7.0'
        run: npm run eslint-check
      - name: code format
        if: matrix.node == '13.7.0'
        run: npm run prettier-check
      # for now keep it after publish package even if it means
      # package will be published at least we knoe if there is a regression
      # Otherwse we would have to reswitch to 13.7 before publishing the package
      - name: Non regression test for node 12.8
        if: runner.os == 'Linux' # runner check to run it once
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm install 12.8.0
          nvm use 12.8.0
          node ./script/test/test.cjs
