# This file configure a GitHub workflow responsible to perform
# various checks related to the codebase.
#
# For that reason it's runned on every pull request and push to main.
#
# It does the following:
#  - Check linting passes (no eslint error on files)
#  - Run tests and ensure none is failing

name: core

on:
  push:
    branches:
      - main
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths
    paths-ignore:
      - "**/README.md"
      - "**/md/**"
      - "**/docs/**"
      - "**/packages/independent/workflow/**"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/README.md"
      - "**/md/**"
      - "**/docs/**"
      - "**/packages/independent/workflow/**"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2022] # https://github.com/actions/runner-images
        node: [22.3.0]
    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.os }} and node ${{ matrix.node }}
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: set linux fs limits
        if: runner.os == 'Linux'
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
          sudo sh -c "ulimit -n 65536 && exec su $LOGNAME"
          ulimit -n
        # sudo ulimit should prevent npm link failure
      - name: Install node modules
        run: npm install
      - name: Install playwright
        run: npx playwright install-deps
      - name: Install certificate # needed for @jsenv/service-worker tests
        if: runner.os == 'Linux' # https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
        run: node ./scripts/test/certificate_install.mjs
      - name: Fix lightningcss windows
        if: runner.os == 'Windows'
        run: npm install lightningcss-win32-x64-msvc
      - name: Run ESLint
        run: npm run eslint
      - name: Run core tests
        run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
