name: performance_impact

on: pull_request

jobs:
  perf_impact:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [19.8.1]
    runs-on: ${{ matrix.os }}
    name: performance impact
    steps:
      - name: Setup git
        uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install node modules
        run: npm install
      - name: Install playwright
        run: npm run playwright:install
      - name: Report performance impact
        run: node --expose-gc ./.github/workflows/pr_impact/report_performance_impact.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
